swagger: '2.0'
produces:
  - application/json
consumes:
  - application/json

paths:
  /repositorySearch:
    post:
      description: |
        Search for potential new repositories to collect
      operationId: searchRepositories
      parameters:
        - name: query
          in: body
          required: true
          schema:
            $ref: '#/definitions/repositorySearchQueryDto'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/repositorySearchResultsDto'
  /repositories/{id}:
    get:
      description: |
        get repository listing by id
      parameters:
        - name: id
          in: path
          description: repositoryId to return
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/repositoryDto'
  /userCollections/{id}:
    get:
      description: |
        gets user collection of repositories by id
      parameters:
        - name: id
          in: path
          description: id of collection to return
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/repositoryDto'

  /userCollections/{id}/ignore:
    post:
      description: |
        Add repository to collection
      operationId: ignoreRepository
      parameters:
        - name: id
          in: path
          description: userRepositoryCollectionId to add dao
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK

  /userCollections/{id}/collect:
    post:
      description: |
        Add repository to collection
      operationId: addRepositoryToUserCollection
      parameters:
        - name: id
          in: path
          description: userRepositoryCollectionId to add dao
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK


definitions:
  repositorySearchResultsDto:
    type: object
    properties:
      totalCount:
        type: integer
        format: int32
      incompleteResults:
        type: boolean
      items:
        type: array
        items:
          $ref: '#/definitions/repositorySearchResultItemDto'


  repositorySearchResultItemDto:
    type: object
    properties:
      id:
        type: integer
        format: int64
      fullName:
        type: string
      description:
        type: string
      url:
        type: string
      stars:
        type: integer
        format: int32

  repositorySearchQueryDto:
    type: object
    properties:
      size:
        type: string
      stars:
        type: string
      language:
        type: string

  userCollectionDto:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      created:
        type: string
      modified:
        type: string
      repositories:
        type: array
        items:
          $ref: '#/definitions/repositoryDto'

  repositoryDto:
    type: object
    properties:
      id:
        type: integer
        format: int64
      fullName:
        type: string
      description:
        type: string
      url:
        type: string
      stars:
        type: integer
        format: int32
      notes:
        type: string
      saved:
        type: string
      updated:
        type: string